development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  host: localhost
  
test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  host: localhost
  
cucumber:
  <<: *TEST
